=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/schema/TicketSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
			elementFormDefault="qualified" 
			targetNamespace="http://example.org/ticket"
			xmlns:tn="http://example.org/ticket">
	
	<!-- XML Schema zum Support-Formular, die ct_anfrage und ct_info unterteil ist,
		 wobei die Anzahl vom Element ct_info mehrfach-->
	
	<!-- Root-Element "Anfrage" mit Attribut "id" und den zugehÃ¶rigen Eigenschaften -->
	<xs:element name="Ticket">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="tn:ct_ticket">
					<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<!-- ComplexType zum Root-Element mit Zwei weiteren Kind-Elementen vom Typ ComplexType -->
	<xs:complexType name="ct_ticket">
		<xs:sequence>
			<xs:element name="Infos" type="tn:ct_info"/>
			<xs:element name="Antworten">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Antwort" type="tn:ct_antwort" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<!-- ComplexType zum Element "Infos"-->
	<xs:complexType name="ct_info">
		<xs:sequence>
			<xs:element name="Betreff" type="xs:string"/>
			<xs:element name="User">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Standort" type="xs:string"/>
			<xs:element name="SupporterList">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Supporter" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="Datum" type="xs:dateTime"/>
			<xs:element name="Beschreibung" type="xs:string"/>
			<xs:element name="Zustand" type="xs:string"/>
			<xs:element name="in_bearbeitung" type="xs:boolean" default="false"/>
			<xs:element name="Tags">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Tag" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<!-- ComplexType zum Element "Antwort" -->
	<xs:complexType name="ct_antwort">
		<xs:sequence>
			<xs:element name="Supporter">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Datum" type="xs:dateTime"/>
			<xs:element name="Antwort" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/tickets/2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Ticket xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="2" xsi:schemaLocation="http://example.org/ticket ../../schema/TicketSchema.xsd">
    <Infos>
        <Betreff>gfdgadfdsf</Betreff>
        <User id="1">Max Mustermann</User>
        <Standort>Max</Standort>
        <SupporterList>
            <Supporter id="1">Max Mustermann</Supporter>
        </SupporterList>
        <Datum>2013-06-21T11:15:30.166+02:00</Datum>
        <Beschreibung>dfsafdsgdfagfddsaf</Beschreibung>
        <Zustand>kritisch</Zustand>
        <in_bearbeitung>false</in_bearbeitung>
        <Tags>
            <Tag>Software</Tag>
        </Tags>
    </Infos>
    <Antworten/>
</Ticket>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/tickets/7.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Ticket xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="7" xsi:schemaLocation="http://example.org/ticket ../../schema/TicketSchema.xsd">
    <Infos>
        <Betreff>vfafds</Betreff>
        <User id="2">Oliver Steinle</User>
        <Standort>Cologne</Standort>
        <SupporterList/>
        <Datum>2013-06-20T18:01:08.383+02:00</Datum>
        <Beschreibung>fafcadscdcfew</Beschreibung>
        <Zustand>niedrig</Zustand>
        <in_bearbeitung>false</in_bearbeitung>
        <Tags>
            <Tag>Hardware</Tag>
        </Tags>
    </Infos>
    <Antworten/>
</Ticket>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/tickets/4.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Ticket xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="4" xsi:schemaLocation="http://example.org/ticket ../../schema/TicketSchema.xsd">
    <Infos>
        <Betreff>fdsfdsfdsaf</Betreff>
        <User id="2">Oliver Steinle</User>
        <Standort>Cologne</Standort>
        <SupporterList>
        </SupporterList>
        <Datum>2013-06-22T09:23:58.826+02:00</Datum>
        <Beschreibung>gdfadsfdsfdsfasfsd</Beschreibung>
        <Zustand>niedrig</Zustand>
        <in_bearbeitung>false</in_bearbeitung>
        <Tags>
            <Tag>Software</Tag>
        </Tags>
    </Infos>
    <Antworten/>
</Ticket>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/tickets/1.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Ticket xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="1" xsi:schemaLocation="http://example.org/ticket ../../schema/TicketSchema.xsd">
    <Infos>
        <Betreff>Internet gelöscht</Betreff>
        <User id="1">Max Mustermann</User>
        <Standort>CGN</Standort>
        <SupporterList>
            <Supporter id="3">Michael Schmidt</Supporter>
        </SupporterList>
        <Datum>2013-05-14T12:27:35</Datum>
        <Beschreibung>Ich habe ausversehen das Internet gelöscht</Beschreibung>
        <Zustand>niedrig</Zustand>
        <Tags>
            <Tag>Hardware</Tag>
        </Tags>
    </Infos>
    <Antworten>
        <Antwort>
            <Supporter id="1"></Supporter>
            <Antwort>test</Antwort>
        </Antwort>
        <Antwort>
            <Supporter id="1"></Supporter>
            <Antwort>test</Antwort>
        </Antwort>
        <Antwort>
            <Supporter id="2"></Supporter>
            <Antwort>hifdsajldsfas</Antwort>
        </Antwort>
        <Antwort>
            <Supporter id="3">Max Mustermann</Supporter>
            <Antwort>hallo</Antwort>
        </Antwort>
    </Antworten>
</Ticket>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/tickets/47.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Ticket xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="47" xsi:schemaLocation="http://example.org/ticket ../../schema/TicketSchema.xsd">
    <Infos>
        <Betreff>gdfagdg</Betreff>
        <User id="7">Oliver Steinle</User>
        <Standort>CGN</Standort>
        <SupporterList/>
        <Datum>2013-06-10T16:22:03.791+02:00</Datum>
        <Beschreibung>fasfagadfvdfg</Beschreibung>
        <Zustand>Niedrig</Zustand>
        <Tags>
            <Tag>Hardware</Tag>
            <Tag>Windows</Tag>
            <Tag>iOS</Tag>
        </Tags>
    </Infos>
    <Antworten/>
</Ticket>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/tickets/29.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Ticket xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="29" xsi:schemaLocation="http://example.org/ticket ../../schema/TicketSchema.xsd">
    <Infos>
        <Betreff>Testbetreff</Betreff>
        <User id="1">Max Mustermann</User>
        <Standort>CGN</Standort>
        <SupporterList>
            <Supporter id="3">Michael Schmidt</Supporter>
        </SupporterList>
        <Datum>2013-06-07T20:59:35.455+02:00</Datum>
        <Beschreibung>Testbeschreibung</Beschreibung>
        <Zustand>normal</Zustand>
        <Tags>
            <Tag>Hardware</Tag>
        </Tags>
    </Infos>
    <Antworten/>
</Ticket>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/tickets/49.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Ticket xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="49" xsi:schemaLocation="http://example.org/ticket ../../schema/TicketSchema.xsd">
    <Infos>
        <Betreff>fsdagfgfd</Betreff>
        <User id="7">Oliver Steinle</User>
        <Standort>CGN</Standort>
        <SupporterList/>
        <Datum>2013-06-10T16:34:58.220+02:00</Datum>
        <Beschreibung>gdfgdfvcvdfg</Beschreibung>
        <Zustand>Normal</Zustand>
        <Tags>
            <Tag>Windows</Tag>
            <Tag>Android</Tag>
        </Tags>
    </Infos>
    <Antworten/>
</Ticket>
