=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/schema/TicketSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
			elementFormDefault="qualified" 
			targetNamespace="http://example.org/ticket"
			xmlns:tn="http://example.org/ticket">
	
	<!-- XML Schema zum Support-Formular, die ct_anfrage und ct_info unterteil ist,
		 wobei die Anzahl vom Element ct_info mehrfach-->
	
	<!-- Root-Element "Anfrage" mit Attribut "id" und den zugehÃ¶rigen Eigenschaften -->
	<xs:element name="Ticket">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="tn:ct_ticket">
					<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	
	<!-- ComplexType zum Root-Element mit Zwei weiteren Kind-Elementen vom Typ ComplexType -->
	<xs:complexType name="ct_ticket">
		<xs:sequence>
			<xs:element name="Infos" type="tn:ct_info"/>
			<xs:element name="Antworten">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Antwort" type="tn:ct_antwort" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<!-- ComplexType zum Element "Infos"-->
	<xs:complexType name="ct_info">
		<xs:sequence>
			<xs:element name="Betreff" type="xs:string"/>
			<xs:element name="User">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Standort" type="xs:string"/>
			<xs:element name="SupporterList">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Supporter" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="Datum" type="xs:dateTime"/>
			<xs:element name="Beschreibung" type="xs:string"/>
			<xs:element name="Zustand" type="xs:string"/>
			<xs:element name="in_bearbeitung" type="xs:boolean" default="false"/>
			<xs:element name="Tags">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Tag" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<!-- ComplexType zum Element "Antwort" -->
	<xs:complexType name="ct_antwort">
		<xs:sequence>
			<xs:element name="Supporter">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="id" type="xs:nonNegativeInteger" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Datum" type="xs:dateTime"/>
			<xs:element name="Antwort" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/tickets/48.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Ticket xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="48" xsi:schemaLocation="http://example.org/ticket ../../schema/TicketSchema.xsd">
    <Infos>
        <Betreff>gfdagdfg</Betreff>
        <User id="7">Oliver Steinle</User>
        <Standort>CGN</Standort>
        <SupporterList/>
        <Datum>2013-06-10T16:30:07.759+02:00</Datum>
        <Beschreibung>gdfgdgdfgdsg</Beschreibung>
        <Zustand>Hoch</Zustand>
        <Tags>
            <Tag>OSX</Tag>
        </Tags>
    </Infos>
    <Antworten/>
</Ticket>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/tickets/40.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Ticket xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="40" xsi:schemaLocation="http://example.org/ticket ../../schema/TicketSchema.xsd">
    <Infos>
        <Betreff>gfdagfdgdf</Betreff>
        <User id="7">Oliver Steinle</User>
        <Standort>CGN</Standort>
        <SupporterList/>
        <Datum>2013-06-10T14:49:14.306+02:00</Datum>
        <Beschreibung>fgfagdfgdfgds</Beschreibung>
        <Zustand>Niedrig</Zustand>
        <Tags>
            <Tag>Software</Tag>
        </Tags>
    </Infos>
    <Antworten/>
</Ticket>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/tickets/3.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Ticket xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="3" xsi:schemaLocation="http://example.org/ticket ../../schema/TicketSchema.xsd">
    <Infos>
        <Betreff>fdsfdsfdsaf</Betreff>
        <User id="1">Max Mustermann</User>
        <Standort>Max</Standort>
        <SupporterList>
            <Supporter id="1">Max Mustermann</Supporter>
        </SupporterList>
        <Datum>2013-06-21T11:15:38.068+02:00</Datum>
        <Beschreibung>gdfadsvabaervfasdf</Beschreibung>
        <Zustand>geschlossen</Zustand>
        <in_bearbeitung>false</in_bearbeitung>
        <Tags>
            <Tag>Hardware</Tag>
        </Tags>
    </Infos>
    <Antworten>
        <Antwort>
            <Supporter id="1">Max Mustermann</Supporter>
            <Datum>2013-06-23T18:20:04.152+02:00</Datum>
            <Antwort>fuck you</Antwort>
        </Antwort>
    </Antworten>
</Ticket>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/tickets/8.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Ticket xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="8" xsi:schemaLocation="http://example.org/ticket ../../schema/TicketSchema.xsd">
    <Infos>
        <Betreff>fvdfsvcfdsv</Betreff>
        <User id="1">Max Mustermann</User>
        <Standort>Max</Standort>
        <SupporterList/>
        <Datum>2013-06-22T22:52:43.030+02:00</Datum>
        <Beschreibung>v  vdfvfdv</Beschreibung>
        <Zustand>normal</Zustand>
        <in_bearbeitung>false</in_bearbeitung>
        <Tags>
            <Tag>Software</Tag>
        </Tags>
    </Infos>
    <Antworten/>
</Ticket>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/tickets/38.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Ticket xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="38" xsi:schemaLocation="http://example.org/ticket ../../schema/TicketSchema.xsd">
    <Infos>
        <Betreff>dritter Test</Betreff>
        <User id="7">Oliver Steinle</User>
        <Standort>CGN</Standort>
        <SupporterList/>
        <Datum>2013-06-10T14:36:12.121+02:00</Datum>
        <Beschreibung>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. </Beschreibung>
        <Zustand>Hoch</Zustand>
        <Tags>
            <Tag>Hardware</Tag>
            <Tag>Windows</Tag>
            <Tag>Android</Tag>
        </Tags>
    </Infos>
    <Antworten/>
</Ticket>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/tickets/46.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Ticket xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="46" xsi:schemaLocation="http://example.org/ticket ../../schema/TicketSchema.xsd">
    <Infos>
        <Betreff>gfdagdfg</Betreff>
        <User id="7">Oliver Steinle</User>
        <Standort>CGN</Standort>
        <SupporterList/>
        <Datum>2013-06-10T16:19:46.047+02:00</Datum>
        <Beschreibung>jlkfjlsfgafsaf</Beschreibung>
        <Zustand>Hoch</Zustand>
        <Tags>
            <Tag>Software</Tag>
            <Tag>OSX</Tag>
            <Tag>Android</Tag>
        </Tags>
    </Infos>
    <Antworten/>
</Ticket>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/tickets/42.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Ticket xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="42" xsi:schemaLocation="http://example.org/ticket ../../schema/TicketSchema.xsd">
    <Infos>
        <Betreff>fdsfdsfg</Betreff>
        <User id="7">Oliver Steinle</User>
        <Standort>CGN</Standort>
        <SupporterList/>
        <Datum>2013-06-10T16:03:13.458+02:00</Datum>
        <Beschreibung>gfdgfdgafdgdf</Beschreibung>
        <Zustand>Normal</Zustand>
        <Tags>
            <Tag>Windows</Tag>
        </Tags>
    </Infos>
    <Antworten/>
</Ticket>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/tickets/39.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Ticket xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="39" xsi:schemaLocation="http://example.org/ticket ../../schema/TicketSchema.xsd">
    <Infos>
        <Betreff>Hallo</Betreff>
        <User id="7">Oliver Steinle</User>
        <Standort>CGN</Standort>
        <SupporterList/>
        <Datum>2013-06-10T14:48:44.342+02:00</Datum>
        <Beschreibung>jlifjdlsafsd</Beschreibung>
        <Zustand>Niedrig</Zustand>
        <Tags>
            <Tag>Windows</Tag>
        </Tags>
    </Infos>
    <Antworten/>
</Ticket>
