=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/schema/TListeSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
			elementFormDefault="qualified" 
			targetNamespace="http://example.org/ticket"
			xmlns:tn="http://example.org/ticket">

	<xs:element name="ticketlist">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="teintrag" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ticket_id" type="xs:nonNegativeInteger"/>
							<xs:element name="ersteller_id" type="xs:nonNegativeInteger"/>
							<xs:element name="betreff" type="xs:string"/>
							<xs:element name="datum" type="xs:dateTime"/>
							<xs:element name="zustand" type="xs:string"/>
							<xs:element name="bearbeitungszustand" type="xs:boolean"/>
							<xs:element name="tags">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="tag" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/ticketliste.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ticketlist xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://example.org/ticket ../schema/TListeSchema.xsd">
    <teintrag>
        <ticket_id>1</ticket_id>
        <betreff>Internet gel√∂scht</betreff>
        <datum>2001-12-31T12:00:00</datum>
        <zustand>niedrig</zustand>
        <tags>
            <tag>Hardware</tag>
        </tags>
    </teintrag>
    <teintrag>
        <ticket_id>2</ticket_id>
        <betreff>Kein Bild</betreff>
        <datum>2001-12-31T12:00:00</datum>
        <zustand>hoch</zustand>
        <tags>
            <tag>Software</tag>
        </tags>
    </teintrag>
    <teintrag>
        <ticket_id>3</ticket_id>
        <betreff>Testbetreff</betreff>
        <datum>2013-05-14T21:47:22.139+02:00</datum>
        <zustand>normal</zustand>
        <tags>
            <tag>Hardware</tag>
        </tags>
    </teintrag>
    <teintrag>
        <ticket_id>4</ticket_id>
        <betreff>Testbetreff</betreff>
        <datum>2013-05-14T21:58:48.263+02:00</datum>
        <zustand>normal</zustand>
        <tags>
            <tag>Hardware</tag>
        </tags>
    </teintrag>
    <teintrag>
        <ticket_id>6</ticket_id>
        <betreff>Testbetreff</betreff>
        <datum>2013-05-14T22:03:22.937+02:00</datum>
        <zustand>normal</zustand>
        <tags>
            <tag>Hardware</tag>
        </tags>
    </teintrag>
    <teintrag>
        <ticket_id>7</ticket_id>
        <betreff>Testbetreff</betreff>
        <datum>2013-05-14T22:04:19.984+02:00</datum>
        <zustand>normal</zustand>
        <tags>
            <tag>Hardware</tag>
        </tags>
    </teintrag>
    <teintrag>
        <ticket_id>8</ticket_id>
        <betreff>Testbetreff</betreff>
        <datum>2013-05-14T22:04:47.879+02:00</datum>
        <zustand>normal</zustand>
        <tags>
            <tag>Hardware</tag>
        </tags>
    </teintrag>
    <teintrag>
        <ticket_id>9</ticket_id>
        <betreff>Testbetreff</betreff>
        <datum>2013-05-14T22:06:15.291+02:00</datum>
        <zustand>normal</zustand>
        <tags>
            <tag>Hardware</tag>
        </tags>
    </teintrag>
</ticketlist>
