=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/schema/UListeSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
			elementFormDefault="qualified" 
			targetNamespace="http://example.org/ticket"
			xmlns:tn="http://example.org/ticket">

	<xs:element name="userdb">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="user" type="tn:ct_profile" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="ct_profile">
		<xs:sequence>
			<xs:element name="id" type="xs:nonNegativeInteger"/>
			<xs:element name="Vorname" type="xs:string"/>
			<xs:element name="Nachname" type="xs:string"/>
			<xs:element name="Standort" type="xs:string"/>
			<xs:element name="status" type="xs:string"/>
			<xs:element name="KnowHows" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="KnowHow" type="tn:stknowhow" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Tickets" type="tn:cttickets"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="cttickets">
		<xs:sequence>
			<xs:element name="ticketId" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="stknowhow">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Hardware"/>
			<xs:enumeration value="Software"/>
			<xs:enumeration value="OSX"/>
			<xs:enumeration value="Windows"/>
			<xs:enumeration value="Netzwerk"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/xml/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<tn:userdb xmlns:tn="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://example.org/ticket ../schema/UListeSchema.xsd ">
  <tn:user>
    <tn:id>u_1</tn:id>
    <tn:Vorname>tn:Vorname</tn:Vorname>
    <tn:Nachname>tn:Nachname</tn:Nachname>
    <tn:Standort>tn:Standort</tn:Standort>
    <tn:admin>true</tn:admin>
    <tn:Tickets/>
  </tn:user>
</tn:userdb>

=== ollsen/wba2SS13Phase2/WBA2Phase2/src/de/steinleostolski/xml/user.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<userdb xmlns="http://example.org/ticket" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://example.org/ticket ../schema/UListeSchema.xsd">
    <user>
        <id>1</id>
        <jabber>admin</jabber>
        <Vorname>Max</Vorname>
        <Nachname>Mustermann</Nachname>
        <Standort>CGN</Standort>
        <status>admin</status>
        <KnowHows>
            <KnowHow>Software</KnowHow>
        </KnowHows>
        <Tickets>
            <ticketId>3</ticketId>
            <ticketId>4</ticketId>
            <ticketId>6</ticketId>
            <ticketId>7</ticketId>
            <ticketId>8</ticketId>
            <ticketId>9</ticketId>
        </Tickets>
    </user>
    <user>
        <id>2</id>
        <jabber>null</jabber>
        <Vorname>Michael</Vorname>
        <Nachname>Schmidt</Nachname>
        <Standort>HAM</Standort>
        <status>user</status>
        <Tickets/>
    </user>
    <user>
        <id>3</id>
        <jabber>ollsen</jabber>
        <Vorname>Michael</Vorname>
        <Nachname>Schmidt</Nachname>
        <Standort>NBG</Standort>
        <status>supporter</status>
        <KnowHows>
            <KnowHow>Hardware</KnowHow>
            <KnowHow>Software</KnowHow>
            <KnowHow>Windows</KnowHow>
        </KnowHows>
        <Tickets>
            <ticketId>3</ticketId>
            <ticketId>4</ticketId>
            <ticketId>6</ticketId>
            <ticketId>7</ticketId>
            <ticketId>8</ticketId>
            <ticketId>9</ticketId>
        </Tickets>
    </user>
    <user>
        <id>4</id>
        <jabber>null</jabber>
        <Vorname>Vorname</Vorname>
        <Nachname>Nachname</Nachname>
        <Standort>CGN</Standort>
        <status>supporter</status>
        <KnowHows>
            <KnowHow>Hardware</KnowHow>
            <KnowHow>Software</KnowHow>
        </KnowHows>
        <Tickets/>
    </user>
</userdb>
